### ISSUE TITLE
Setup to hide app label from gschema.override

### ISSUE THREAD

**Issue by ivoarch** [michael-rapp/gnome-shell-extension-hide-app-icon#1]
Hi,
I need to setup to hide app label from **/usr/share/glib-2.0/schemas/my.gschema.override**  file on GNOME 3.14 CentOS 7.2.

Like thise
```
[org.gnome.shell.extensions.hide-app-icon]
hide-app-label=true
```

Then rebuild schema cache with any overrides
```
glib-compile-schemas /usr/share/glib-2.0/schemas
```

But this does not work and the app label is shown again?
If I have understood well the bolean of **hide-app-icon** is default setup to **true** others to **false** ?
Any idea?

screenshot: [here](http://storage4.static.itmages.ru/i/16/1128/h_1480324827_5581642_ea3a532642.png)

**Comment by michael-rapp** [comment]
Hi,

so you want to override the extension's settings from another gschema file? Is this why you want to change the default for new users (as discussed [here](http://askubuntu.com/questions/65900/how-can-i-change-default-settings-for-new-users))?

Does the override file actually change the default values, but the extension still shows the label? Or do the default values remain the same? If the default values change, but the extension does not adapt to them, restarting the extension might help. You can either restart GNOME shell via Alt + F2 and by entering "r", disable the extension and re-enable it, or logging out and in again.

Besides, you are correct about the default values. They can be seen in the extension's [gschema file](https://github.com/michael-rapp/gnome-shell-extension-hide-app-icon/blob/master/hide-app-icon%40mrapp.sourceforge.com/schemas/org.gnome.shell.extensions.hide-app-icon.gschema.xml). Maybe you can try, if the settings change correctly when editing this file. Don't forget to recompile the schema and to restart the extension.

**Comment by ivoarch** [comment]
Yes, I want to override the extension's settings from another gschema file from /usr/share/glib-2.0/schemas /. But tested the new settings from clean environment the default values are the same . The gnome-tweak-tool shows the extension default value (hide-app-icon is set to true , other to false) . 
The strange thing is that dconf-editor shows that all values is set to true , like my gschema file . See the screenshot of my first post .

I've tried `[Alt+F2 r]`, but does not work , it only works putting the values from gnome-tweak .

Other settings from the same gscheme file works!! 

Here my gschema.

```
cat >> /usr/share/glib-2.0/schemas/org.my.gschema.override << FOE
[org.gnome.shell.extensions.hide-app-icon]
hide-app-label=true
hide-arrow=true

[org.gnome.shell.extensions.panel-osd]
x-pos=96.0
y-pos=96.0
force-expand=true
---8>-----8>----
more ...
FOE

# rebuild schema cache with any overrides we installed
glib-compile-schemas /usr/share/glib-2.0/schemas
```

Compiling the schema does not show any error .

**Comment by michael-rapp** [comment]
If the values are set correctly in gconf editor, the problem must be in how the extension accesses these values. Unfortunately, I've got only very few time for testing this out at the moment. 

If you want, you can try the following:

- Edit the [prefs.js](https://github.com/michael-rapp/gnome-shell-extension-hide-app-icon/blob/master/hide-app-icon%40mrapp.sourceforge.com/prefs.js) file of your local installation
- Go to line 39: `this._settings = Convenience.getSettings();`
- Replace it with: ``this._settings = Convenience.getSettings('org.gnome.shell.extensions.hide-app-icon');``
- Reload the extension and test if it solves the problem.

This is just an idea, I am not sure, if it solves the problem.

**Comment by ivoarch** [comment]
Thanks. I will try later!
edit: The same problem :(

**Comment by ivoarch** [comment]
FInally I fixed by enabling all values to 'true' in gschema.xml file and rebuild and install the new theme.
[1] https://gist.github.com/ivoarch/4ee43b75e1725fd62f0f448c378c1457 This resolves the issue for me, is a bit forced but it works . 

Thanks!
