### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by amivaleo** [michael-rapp/gnome-shell-extension-hide-app-icon#2]
Hi!
I would like to translate this extension in my native language (italian).
Could you please add the "locale" folder and the pot file please? :)

**Comment by michael-rapp** [comment]
To implement multi-language support, I created a new branch at https://github.com/michael-rapp/gnome-shell-extension-hide-app-icon/tree/multi-language-support. I added a pot file as well as German translation (that's my native language). Please submit a pull request for said branch, which adds the Italian po file `locale/it/LC_MESSAGES/hide-app-icon.po`.

**Comment by michael-rapp** [comment]
Now that your pull request (https://github.com/michael-rapp/gnome-shell-extension-hide-app-icon/pull/3) has been merged, you might want to checkout the branch and test it on your system. It would be great, if you could confirm that the translation works correctly. It is the first time for me to add multi-language support to a shell extension and I am not one-hundred percent sure that we got everything that it needs.

**Comment by amivaleo** [comment]
Sure!
I'm going to check that. Give me a few minutes! ;)

**Comment by amivaleo** [comment]
It doesn't work.
I completely replaced the contents of my local folders with the updated files in your repo. The extension settings are not translated in italian, still they are in english.

Does it work with german language?

**Comment by michael-rapp** [comment]
No, it doesn't work either :-( We must have missed something. I will take a look at other extensions to see how they get it working. Or do you have any idea?

**Comment by amivaleo** [comment]
I can't help. :(
I would like to learn how to make extension. Their script are almost unreadable to me.
I'm comparing your files with others from other extensions, but it's just a trial and error...

I will let you know if I find the solution.

**Comment by michael-rapp** [comment]
I think I got it! At least the German translation works on my system. Please checkout the branch again and give it a try!

**Comment by michael-rapp** [comment]
@amivaleo Did you test it?

**Comment by amivaleo** [comment]
I can't test it yet. :/
My internet connection is not working. I can only use my mobile data now.
I'll test it as soon as I can. I'm sorry...

**Comment by michael-rapp** [comment]
Alright, tell me the results as soon you are able to test it. Maybe you can use a wifi hotspot from your phone to download the extension. It is not that large ;-)

**Comment by amivaleo** [comment]
Ok, I've done that. It works! It's translated in Italian now. :)

How did you learn making gnome extension? I would like to learn, but I just can't without a reference guide. Did you find some manual or video or anything...?

**Comment by michael-rapp** [comment]
I am glad to hear, that it now works. I will prepare a new release on Github and extensions.gnome.org soon. I will close this issue once the release is done.

If you want to make your own shell extensions, it's good to know the basics of JavaScript. Unfortunately there is only few documentation on how to implement extensions (e.g. [here](https://wiki.gnome.org/Projects/GnomeShell/Extensions) or [here](https://wiki.gnome.org/Projects/GnomeShell/Extensions/StepByStepTutoria)). What really helps is to take a look at the code of other extensions and use Looking Glass to identify the UI elements you want to modify. But overall, it is really painfull for beginners due to the lack of good tutorials, I think.

**Comment by amivaleo** [comment]
Yes, it's very hard indeed. :(
Thank you for the two references, that can be a good starting point.

I'm glad I could help in translating your extension. ;)

**Comment by michael-rapp** [comment]
The translations are now released in version 2.6 on [Github](https://github.com/michael-rapp/gnome-shell-extension-hide-app-icon/releases) as well as on [extensions.gnome.org](https://extensions.gnome.org/extension/810/hide-app-icon/). The latter takes some time until it is available as the new version must be reviewed beforehand.
